// "use client";



// import localFont from "next/font/local";
// import "./globals.css";
// import { QueryClient, QueryClientProvider } from 'react-query';

// const queryClient = new QueryClient();

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }


// export default function Layout({ children }) {
// 	return (
// 	  <QueryClientProvider client={queryClient}>
// 		 {children}
// 	  </QueryClientProvider>
// 	);
//  }


// 'use client'


// // app/layout.js (or RootLayout.js)
// import localFont from "next/font/local";
// import "./globals.css";
// import NavBar from "./_components/navbar";
// import { Provider } from 'react-redux';
// // import store from '@/redux/store';
// import store from "./redux/store";



// // Import your fonts
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });
// 'use server'
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
			
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
// 			<Provider store={store}>
// 				<NavBar />
// 				{children}
// 			</Provider>
//       </body>
//     </html>
//   );
// }// app/layout.jsx








import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./_components/navbar";
// import ClientProvider from "./_components/ClientProvider"; // Import ClientProvider
import ClientProvider from "./_components/clientprovider";
import Footer from "./_components/footer";
// import { metadata } from "./metadata"; // Separate metadata if needed

// Import your fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProvider> {/* Wrap content with ClientProvider */}
          <NavBar />
          {children}
			 <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}






